/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as ParrainageRouteImport } from './routes/parrainage'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as InscriptionChauffeurRouteImport } from './routes/inscription-chauffeur'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const ParrainageRoute = ParrainageRouteImport.update({
  id: '/parrainage',
  path: '/parrainage',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionChauffeurRoute = InscriptionChauffeurRouteImport.update({
  id: '/inscription-chauffeur',
  path: '/inscription-chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursRoute = ChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/documents': typeof DocumentsRoute
  '/historique': typeof HistoriqueRoute
  '/inscription-chauffeur': typeof InscriptionChauffeurRoute
  '/paiements': typeof PaiementsRoute
  '/parrainage': typeof ParrainageRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/documents': typeof DocumentsRoute
  '/historique': typeof HistoriqueRoute
  '/inscription-chauffeur': typeof InscriptionChauffeurRoute
  '/paiements': typeof PaiementsRoute
  '/parrainage': typeof ParrainageRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/documents': typeof DocumentsRoute
  '/historique': typeof HistoriqueRoute
  '/inscription-chauffeur': typeof InscriptionChauffeurRoute
  '/paiements': typeof PaiementsRoute
  '/parrainage': typeof ParrainageRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/documents'
    | '/historique'
    | '/inscription-chauffeur'
    | '/paiements'
    | '/parrainage'
    | '/securite'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/documents'
    | '/historique'
    | '/inscription-chauffeur'
    | '/paiements'
    | '/parrainage'
    | '/securite'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/documents'
    | '/historique'
    | '/inscription-chauffeur'
    | '/paiements'
    | '/parrainage'
    | '/securite'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChauffeursRoute: typeof ChauffeursRoute
  ClientsRoute: typeof ClientsRoute
  CourseRoute: typeof CourseRoute
  DocumentsRoute: typeof DocumentsRoute
  HistoriqueRoute: typeof HistoriqueRoute
  InscriptionChauffeurRoute: typeof InscriptionChauffeurRoute
  PaiementsRoute: typeof PaiementsRoute
  ParrainageRoute: typeof ParrainageRoute
  SecuriteRoute: typeof SecuriteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parrainage': {
      id: '/parrainage'
      path: '/parrainage'
      fullPath: '/parrainage'
      preLoaderRoute: typeof ParrainageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-chauffeur': {
      id: '/inscription-chauffeur'
      path: '/inscription-chauffeur'
      fullPath: '/inscription-chauffeur'
      preLoaderRoute: typeof InscriptionChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs': {
      id: '/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/chauffeurs'
      preLoaderRoute: typeof ChauffeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChauffeursRoute: ChauffeursRoute,
  ClientsRoute: ClientsRoute,
  CourseRoute: CourseRoute,
  DocumentsRoute: DocumentsRoute,
  HistoriqueRoute: HistoriqueRoute,
  InscriptionChauffeurRoute: InscriptionChauffeurRoute,
  PaiementsRoute: PaiementsRoute,
  ParrainageRoute: ParrainageRoute,
  SecuriteRoute: SecuriteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
