/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursRoute = ChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/paiements': typeof PaiementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/paiements': typeof PaiementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/paiements': typeof PaiementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/paiements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/chauffeurs' | '/clients' | '/course' | '/paiements'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/paiements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChauffeursRoute: typeof ChauffeursRoute
  ClientsRoute: typeof ClientsRoute
  CourseRoute: typeof CourseRoute
  PaiementsRoute: typeof PaiementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs': {
      id: '/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/chauffeurs'
      preLoaderRoute: typeof ChauffeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChauffeursRoute: ChauffeursRoute,
  ClientsRoute: ClientsRoute,
  CourseRoute: CourseRoute,
  PaiementsRoute: PaiementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
