/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as InscriptionChauffeurRouteImport } from './routes/inscription-chauffeur'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SecuriteRoute = SecuriteRouteImport.update({ id: '/securite', path: '/securite', getParentRoute: () => rootRouteImport } as any)
const PaiementsRoute = PaiementsRouteImport.update({ id: '/paiements', path: '/paiements', getParentRoute: () => rootRouteImport } as any)
const HistoriqueRoute = HistoriqueRouteImport.update({ id: '/historique', path: '/historique', getParentRoute: () => rootRouteImport } as any)
const InscriptionChauffeurRoute = InscriptionChauffeurRouteImport.update({ id: '/inscription-chauffeur', path: '/inscription-chauffeur', getParentRoute: () => rootRouteImport } as any)
const CourseRoute = CourseRouteImport.update({ id: '/course', path: '/course', getParentRoute: () => rootRouteImport } as any)
const ClientsRoute = ClientsRouteImport.update({ id: '/clients', path: '/clients', getParentRoute: () => rootRouteImport } as any)
const ChauffeursRoute = ChauffeursRouteImport.update({ id: '/chauffeurs', path: '/chauffeurs', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/inscription-chauffeur': typeof InscriptionChauffeurRoute
  '/historique': typeof HistoriqueRoute
  '/paiements': typeof PaiementsRoute
  '/securite': typeof SecuriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/inscription-chauffeur': typeof InscriptionChauffeurRoute
  '/historique': typeof HistoriqueRoute
  '/paiements': typeof PaiementsRoute
  '/securite': typeof SecuriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/clients': typeof ClientsRoute
  '/course': typeof CourseRoute
  '/inscription-chauffeur': typeof InscriptionChauffeurRoute
  '/historique': typeof HistoriqueRoute
  '/paiements': typeof PaiementsRoute
  '/securite': typeof SecuriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/inscription-chauffeur'
    | '/historique'
    | '/paiements'
    | '/securite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/inscription-chauffeur'
    | '/historique'
    | '/paiements'
    | '/securite'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chauffeurs'
    | '/clients'
    | '/course'
    | '/inscription-chauffeur'
    | '/historique'
    | '/paiements'
    | '/securite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChauffeursRoute: typeof ChauffeursRoute
  ClientsRoute: typeof ClientsRoute
  CourseRoute: typeof CourseRoute
  InscriptionChauffeurRoute: typeof InscriptionChauffeurRoute
  HistoriqueRoute: typeof HistoriqueRoute
  PaiementsRoute: typeof PaiementsRoute
  SecuriteRoute: typeof SecuriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/securite': { id: '/securite'; path: '/securite'; fullPath: '/securite'; preLoaderRoute: typeof SecuriteRouteImport; parentRoute: typeof rootRouteImport }
    '/paiements': { id: '/paiements'; path: '/paiements'; fullPath: '/paiements'; preLoaderRoute: typeof PaiementsRouteImport; parentRoute: typeof rootRouteImport }
    '/historique': { id: '/historique'; path: '/historique'; fullPath: '/historique'; preLoaderRoute: typeof HistoriqueRouteImport; parentRoute: typeof rootRouteImport }
    '/inscription-chauffeur': { id: '/inscription-chauffeur'; path: '/inscription-chauffeur'; fullPath: '/inscription-chauffeur'; preLoaderRoute: typeof InscriptionChauffeurRouteImport; parentRoute: typeof rootRouteImport }
    '/course': { id: '/course'; path: '/course'; fullPath: '/course'; preLoaderRoute: typeof CourseRouteImport; parentRoute: typeof rootRouteImport }
    '/clients': { id: '/clients'; path: '/clients'; fullPath: '/clients'; preLoaderRoute: typeof ClientsRouteImport; parentRoute: typeof rootRouteImport }
    '/chauffeurs': { id: '/chauffeurs'; path: '/chauffeurs'; fullPath: '/chauffeurs'; preLoaderRoute: typeof ChauffeursRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AdminRoute, AuthRoute, ChauffeursRoute, ClientsRoute, CourseRoute,
  InscriptionChauffeurRoute, HistoriqueRoute, PaiementsRoute, SecuriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
